[global]
workgroup = WORKGROUP
server string = Vulnerable IoT Device
security = user
map to guest = Bad User
log file = /var/log/samba/smb.log
max log size = 50
log level = 1 auth:2


server min protocol = SMB2
client min protocol = SMB2
ntlm auth = ntlmv1-permitted

[share]
path = /srv/share
browseable = yes
writable = yes
guest ok = yes
read only = no
